### PR TITLE
Increase max length to 190

### PR DESCRIPTION
**Pull request by iwiznia**
Context https://expensify.slack.com/archives/C03TQ48KC/p1627495279311100

### CODE REVIEW

**Comment by iwiznia** [comment]
Poll is 16 for changing vs 5 for not: https://expensify.slack.com/archives/C03TQ48KC/p1627495279311100
I think we can merge this now

**Comment by iwiznia** [comment]
Are we ok to merge this now @tgolen?

**Review by tgolen — APPROVED** [review]

**Comment by iwiznia** [comment]
Oh wait, I think I fucked up, I needed to increase the version, no?

**Comment by tgolen** [comment]
Oh, haha, yeah.

**Comment by iwiznia** [comment]
Yeah... doing that now. PR incoming.

**Pull request merged**
