### PR TITLE
Add Custom Rules

### PR DESCRIPTION
**Pull request by marcaaron**
## Custom rules added

- `no-api-in-views` prevents calling `API` directly inside a view
- `no-inline-named-export`
- `no-negated-variables` errors on negated variables
- `no-thenable-actions-in-views` - chaining promises of actions is not allowed
- `no-useless-compose` - using compose with one argument
- `prefer-actions-set-data` - setting Onyx data outside of an action is not allowed
- `prefer-early-return` - encourage early return
- `prefer-onyx-connect-in-libs` - using Onyx.connect() outside of `libs` is not allowed
- `prefer-underscore-method` - prefer underscore methods over native

There's one rule I am adding here, but haven't included yet because it will trigger a ton of changes (trying to stagger this a bit)

`prefer-import-module-contents`

## Non-custom rules added

- no nullish coalescing operator
- no optional chaining
- `jsx-filename-extension` moved over from `Expensify/App`
- `comma-dangle` rule moved over from `Expensify/App`

## Adding our own "plugin"

In order to include the rules in `eslint-config-expensify` we need to use a package like this:

https://github.com/not-an-aardvark/eslint-plugin-rulesdir

An alternative would be to publish a new repository called `eslint-plugin-expensify`, but we can always do that later. The important thing is that the rules be made available in other repos. Having the plugin be it's own repository also seems harder to maintain so I opted to add them here.

## sha syntax in package.json

Rather than publish a new version I decided to start using the sha in the linked `Expensify/App` PR

https://github.com/Expensify/App/pull/6174

## Tests

- Each rule has it's own test (the testable ones at least)

## Todo

There are a few other non custom rules that I've left out for now namely:

```
'import/prefer-default-export': 0,
'import/group-exports': 'error',
'react/destructuring-assignment': [2, 'never'],
```

There will be a _lot_ of changes when those get turned on and I mainly wanted to focus on the custom rules for now 😅

### CODE REVIEW

**Comment by marcaaron** [comment]
cc @johnmlee101 since your suggestion sent me on this journey 😄

**Comment by AndrewGable** [comment]
Wow! Awesome!!

**Review by AndrewGable — COMMENTED** [review]
This looks great, especially the tests. Only found a few nit picks.

**Comment by marcaaron** [comment]
Updated! 

No rush on this, but there's a linked PR with a million zillion changes and is probably going to pile up with conflicts. Honestly, not sure why I did that to myself... I think I optimistically figured this would get instantly merged 😄

**Review by AndrewGable — DISMISSED** [review]

**Review by tgolen — APPROVED** [review]
Looks great! Does the version need to be bumped? Also, it would be cool to have an SO created to provide resources on how to write the ESLint plugins. Some of that stuff you shared with me was really helpful.

**Comment by marcaaron** [comment]
Bumped! Though I am curious if we maybe want to start using the sha based on this unresolved conversation here -> https://github.com/Expensify/Expensify/issues/147306

**Review by AndrewGable — APPROVED** [review]

**Comment by marcaaron** [comment]
Added an SO here https://stackoverflow.com/c/expensify/questions/11317/11318

**Pull request merged**
