### PR TITLE
Disallow arrow functions in props & update dependencies

### PR DESCRIPTION
**Pull request by fnwbr**
@tgolen, will you please review this?

### CODE REVIEW

**Comment by tgolen** [comment]
I am a bit worried about all the changes which will fall out from not allowing arrow methods in the JSX. I think it's a good change, but I also think we need to understand and know how to handle those and move forward.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

This has a few pro-tips, and I am fine with the pro tip about list items in general, but in practice I think we're going to find ourselves in the situation where we are asking ourselves "Do I really have to create a separate component just to do this one method that way?" I want to be sure that everyone is on board with this before moving forward.

If we do find ourselves creating lots of small components to work around this, we also need to consider:

1. Should those be in separate files?
1. Can you define them in the same file as long as it's only used by that file?
1. If they are in a separate file should we put that file in the `components` folder or should it live next to the file that's using it? (this kind of goes back to the question about whether or not it is re-used I guess)

cc @iwiznia @nkuoch @chiragsalian for opinions

**Comment by tgolen** [comment]
Here is an interesting use case to consider which doesn't really make sense to use the "make it a component" alternative:

https://github.com/Expensify/Web-Expensify/pull/18588/files#diff-29a5b5080666f815b122a79698c34b8dR238

I think in this case you would implement `onClick={this.prevPage}` and `onClick={this.nextPage}`, right?

**Comment by fnwbr** [comment]
I'd suggest to un-do the addition of [this rule here](https://github.com/Expensify/eslint-config-expensify/pull/2/files#diff-247bab1370474aabb530240274c4e341R10) again.
That way we don't have to worry about any of what you said above at this point of time + we follow Airbnb in one more place.

That would mean we would
1. error on using `.bind` in props (including refs)
1. allow using arrow functions in props (including refs)

which is what we were always doing up to this point.

**Comment by tgolen** [comment]
That works for me yeah

**Comment by fnwbr** [comment]
Updated

**Pull request merged**
