### PR TITLE
Disable vars-on-top rule

### PR DESCRIPTION
**Pull request by cead22**
@tgolen is this how this is done? Is there a way to test?
Fixes https://github.com/Expensify/Expensify/issues/88662

### CODE REVIEW

**Comment by tgolen** [comment]
Yeah, this looks right. Would you mind updating the readme to clarify the things you were unsure of? I think if we just add a "How to Develop" section, and have it be as simple as:

1. Make a change
1. Bump the version in `package.json`
1. Once PR is merged, create a PR in Web-E and Web-S to update the version

**Comment by cead22** [comment]
Updated

**Comment by fnwbr** [comment]
No need to bump a version in `package.json`, just need to update the lockfile. `npm update eslint-config-expensify` should do the trick.

**Comment by cead22** [comment]
Thank you, updated! Let me know if you think I should add a note for committing the package.lock file on web and web secure after running `npm update eslint-config-expensify`

**Comment by iwiznia** [comment]
Love it! Too bad a lot of the harm is already done...

**Pull request merged**
