### PR TITLE
Reenable no-static-element-interactions

### PR DESCRIPTION
**Pull request by objectsforheads**
@tgolen will you please review this?

Reenabling the no static interaction rule.

### CODE REVIEW

**Comment by fnwbr** [comment]
@objectsforheads Do we still want this?
If so, can you maybe explain a little or link to the code change that made us want to do this?

**Comment by objectsforheads** [comment]
@fnwbr https://github.com/Expensify/Web-Expensify/pull/22030#discussion_r214367709 😅

**Comment by objectsforheads** [comment]
@tgolen updated version - do I need to update dependencies or anything?

**Comment by tgolen** [comment]
We just added some more info to the readme in this repo which should hopefully answer your question. If it doesn't, please let me know!

https://github.com/Expensify/eslint-config-expensify#how-to-develop

Also, you have a conflict now :grin:

**Comment by cead22** [comment]
> you have a conflict now

Sorry ;)

**Comment by objectsforheads** [comment]
updated version. I went for minor since changing our minds sounds like "new functionality" 🤷‍♂️

**Pull request merged**
