### PR TITLE
no-use-state-initializer-functions rule

### PR DESCRIPTION
**Pull request by rezkiy37**
This PR implements a new ESLint rule to detect and restricts usage initializer functions for useState in E/App. Basically, when a function is being called directly within the useState hook, which means it gets executed on every render, even though it only needs to run during the initial state setup. 

```javascript
const [state, setState] = useState(initStateFunc());
``` 

We can pass a callback to the useState hook instead. This ensures the function is only executed once during the initial render, improving performance:

```javascript
const [state, setState] = useState(() => initStateFunc());
``` 

By making this change, e.g. **BottomTabBar** avoids unnecessary re-execution of `getChatTabBrickRoad` on every render. This optimization reduces the render time from approximately `±500ms` to just `50-100ms`, resulting in a more than 5x performance improvement (https://github.com/Expensify/App/pull/53201). This ESLint rule detects these situations to avoid such perf. problems like https://github.com/Expensify/App/issues/53162.

**Issue:** https://github.com/Expensify/App/issues/53322, https://github.com/Expensify/App/issues/53162

### Tests
1. Checkout this branch.
2. Go to E/App repo and run this command to link your `eslint-config-expensify` repo to E/App: `npx link publish <path-to-eslint-repo>/`.
3. Make change in a file that has plenty of examples e.g. `src/components/TimePicker/TimePicker.tsx`, and commit that file.
```diff
+ const [hours, setHours] = useState(DateUtils.get12HourTimeObjectFromDate(value, showFullFormat).hour);
+ const [minutes, setMinutes] = useState(DateUtils.get12HourTimeObjectFromDate(value, showFullFormat).minute);
+ const [seconds, setSeconds] = useState(DateUtils.get12HourTimeObjectFromDate(value, showFullFormat).seconds);
+ const [milliseconds, setMilliseconds] = useState(DateUtils.get12HourTimeObjectFromDate(value, showFullFormat).milliseconds);
+ const [amPmValue, setAmPmValue] = useState(DateUtils.get12HourTimeObjectFromDate(value, showFullFormat).period);
``` 
4. Run `npm run lint-changed`, assert the errors were reported.

<details><summary>Screenshots</summary>

Screenshot 2024-11-29 at 16 23 21
Screenshot 2024-11-29 at 16 23 52

</details>

### CODE REVIEW

**Comment by rezkiy37** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rezkiy37** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alitoshmatov** [comment]
@rezkiy37 I think we should also cover a case where `useState(condition?a():b())`. Based on my testing this is not handled

**Comment by rezkiy37** [comment]
@alitoshmatov, done - fa4c5fd.

**Review by alitoshmatov — APPROVED** [review]
LGTM!

Screenshots
<details>
Screenshot 2024-12-02 at 11 43 37 PM
Screenshot 2024-12-02 at 11 45 31 PM
Screenshot 2024-12-02 at 11 45 39 PM
Screenshot 2024-12-02 at 11 52 58 PM
Screenshot 2024-12-02 at 11 53 10 PM
</details>

**Review by mountiny — APPROVED** [review]
Thanks! lets get this in App now 🚀

**Comment by rezkiy37** [comment]
I've pushed commits forcefully to sign them.

cc @alitoshmatov @mountiny

**Pull request merged**
