### PR TITLE
prefer-underscore-method exception for React.Children.map

### PR DESCRIPTION
**Pull request by roryabraham**
Fixes https://github.com/Expensify/App/issues/7447

Automated tests added.

### CODE REVIEW

**Review by luacmartins — DISMISSED** [review]
Nice! LGTM! Thanks @roryabraham!

**Review by marcaaron — APPROVED** [review]

**Comment by marcaaron** [comment]
bump the version?

**Comment by luacmartins** [comment]
Nice catch @marcaaron!

**Comment by roryabraham** [comment]
Lol I always forget 😓 

At some point I want to set up GitHub Actions here to just bump the version and publish straight to npm.

**Comment by roryabraham** [comment]
Version bumped!

**Review by luacmartins — APPROVED** [review]

**Comment by luacmartins** [comment]
Merging since Marc's only comment was addressed.

**Comment by roryabraham** [comment]
[Pinged in slack](https://expensify.slack.com/archives/C07J32337/p1643330749832339) to get this deployed.

**Comment by roryabraham** [comment]
Published in `2.0.23`

**Pull request merged**
