### PR TITLE
Enforce period only if more than one sentence

### PR DESCRIPTION
**Pull request by carlosmiceli**
Updating rule after this conversation: https://github.com/Expensify/App/pull/44418/files#r1659334495

### CODE REVIEW

**Comment by carlosmiceli** [comment]
@MonilBhavsar wasn't sure how to test it, but it's a simple one anyway.

**Comment by MonilBhavsar** [comment]
Would be good to test.
I think we can use `npm link` or can simply do `npm install git+https://github.com/Expensify/eslint-config-expensify.git#COMMIT`

**Comment by MonilBhavsar** [comment]
Can we also please add some tests in `eslint-plugin-expensify/tests/use-periods-error-messages.test.js`

**Comment by carlosmiceli** [comment]
@MonilBhavsar added the tests! However, I ran `npm link` and `npm install git+https://github.com/Expensify/eslint-config-expensify.git#COMMIT` from `App` and it pretty much broke the tests because I'm ~80 errors when running `npm run lint`... What am I doing wrong?

**Comment by carlosmiceli** [comment]
Oh, wait, I'm also getting those errors running `npm run lint` on `main`... I guess I'm a bit confused as to how to test it.

**Comment by MonilBhavsar** [comment]
> from App and it pretty much broke the tests because I'm getting ~80 errors when running npm run lint... What am I doing wrong?

Do you please mind sharing the failures.

I think it is because the error messages in App are not as per the new rules?

**Comment by MonilBhavsar** [comment]
Thanks for adding the tests!

**Comment by carlosmiceli** [comment]
> I think it is because the error messages in App are not as per the new rules?

Right, but I thought that linking it was supposed to make those tests run according to the changes. Below are the errors, am I missing something?:

```
/Users/carlosmiceli/Expensidev/App/src/languages/en.ts
   780:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
   781:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
   782:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1636:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1637:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1638:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1639:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1640:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1642:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1643:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1644:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1645:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1646:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1647:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1648:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1649:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1650:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1651:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1652:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1653:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1654:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1656:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1657:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1658:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1659:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1660:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1661:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages
  1662:13  error  Use periods at the end of error messages  rulesdir/use-periods-for-error-messages

✖ 105 problems (105 errors, 0 warnings)
  28 errors and 0 warnings potentially fixable with the `--fix` option.

➜  app git:(cm-fix-languages-en/es) ✗ npm link

up to date, audited 3 packages in 3s

found 0 vulnerabilities
```

**Comment by MonilBhavsar** [comment]
Hey Carlos! I tested locally and could not see any errors, which I think is also wrong because we expect to see some error, right?
I think it would be great to jump on a call so we can have a quick look on this. What do you think?

**Comment by carlosmiceli** [comment]
@MonilBhavsar good idea! Put some time on your cal for tomorrow, hope that time works for you?

**Review by MonilBhavsar — APPROVED** [review]
Looks good and works fine, thanks!

**Pull request merged**
